language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g grunt-cli
env:
  global:
    - secure: bwJWLOcSmGcqrzBtgJ44rBlbo89s5wccoV5SoCjnWh1+pZ06nQ0ckIc3CW2pudfb1c1Z9F44SHm0gG0EqTTt8YP9p/LTg33dSF+iLSk7s+Rfv9D70vBr8wNudMUKEjA8bwwCMibajj7ywqtiVyREsrsYW6Wy0lQEXYOPqgU3vd0=
    - secure: DpHWGFlAFBqOqLL2t3eSudtbrGZSobUaKjXQi39B4ZTEorSD1vMcrZcE2kP3emcoCR5HsFt7TLuKnKW5xaSIJdpWOK+O2bkZvMlbGOH6p3OsfkrhBGAi/Ubjk2XYDFZmMG00/teVYbqQ3BWDofrb+RnO5yc8bcwCIE0cuwOICLc=
