# Site settings
title: mom
email: eder.alexan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dynamic Loading of Javascript based on DOM elements.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mom.js.org" # the base hostname & protocol for your site
github_username:  mom

# Build settings
markdown: kramdown
